[environments.default]
store = "theme-evolution-os2.myshopify.com"
theme = 138872651872
path = "./"

[environments.production]
store = "theme-evolution-os2.myshopify.com"
theme = "live"

[ignore]
patterns = [
  "*.txt",
  "config/settings_data.json",
  "templates/*.json",
  "sections/*.json",
  ".git/*",
  "node_modules/*"
]
